esphome:
  name: keller_relay
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keller Relay Fallback Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin: GPIO13

binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_press:
      - light.toggle: light_1
  - platform: gpio
    id: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_press:
      - light.toggle: light_2
  - platform: gpio
    id: button_3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_press:
      - light.toggle: light_3
  - platform: gpio
    id: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_press:
      - light.toggle: light_4
  - platform: status
    name: "Sonoff 4CH Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: gpio
    pin: GPIO4
    id: relay_3
  - platform: gpio
    pin: GPIO15
    id: relay_4

light:
  - platform: binary
    name: "Treppenhaus"
    id: light_1
    output: relay_1

  - platform: binary
    name: "Terrasse"
    id: light_2
    output: relay_2

  - platform: binary
    name: "Garten (Seite)"
    id: light_3
    output: relay_3

  - platform: binary
    id: light_4
    name: "Garten (Hinten)"
    output: relay_4