esphome:
  name: sonoff_beamer
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff Beamer"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    internal: true
    on_press:
      then:
        - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

switch:
  - platform: gpio
    name: "Sonoff S20 Relay"
    pin: GPIO12
    id: relay


status_led:
  pin:
    number: GPIO13
    inverted: yes