esphome:
  name: water_bottles
  platform: ESP8266
  board: d1_mini


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water Bottles"
    password: !secret ap_fallback_password

captive_portal:

api:
ota:
logger:

sensor:
  - platform: hx711
    name: "water_bottles_weight"
    id: water_bottles_weight
    dout_pin: D2
    clk_pin: D1
    gain: 128
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 18595 -> 0
          - -296403 -> 12840
    unit_of_measurement: g

  - platform: template
    name: "water_bottles_count"
    lambda: |-
      auto n = floor(id(water_bottles_weight).state / 1000);
      if (n > 0) return n;
      return 0;
    update_interval: 60s
    accuracy_decimals: 0
    
  - platform: uptime
    name: Water Bottles Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Water Bottles WiFi Signal
    update_interval: 60s
    
switch:
  # Switch to restart the doorbell.
  - platform: restart
    name: Water Bottles Restart
