version: "3"
services:
  # rhasspy-app-time:
  #   build: apps/rhasspy-app-time/
  #   env_file:
  #     - ./.env
  rhasspy-app-weather:
    build: apps/rhasspy-app-weather/
    env_file:
      - ./.env